<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HP-LAPTOP" failures="2" tests="3" name="Error Validations" time="15.715" errors="0" timestamp="2024-07-11T16:00:21 IST">
  <testcase classname="PracticeFrameWork.Tests.ErrorValidations" name="ProductErrorValidation" time="4.866"/>
  <testcase classname="PracticeFrameWork.Tests.ErrorValidations" name="loginErrorValidation" time="6.438">
    <failure type="java.lang.AssertionError" message="expected [] but found [Invalid email or password.]">
      <![CDATA[java.lang.AssertionError: expected [] but found [Invalid email or password.]
at PracticeFrameWork.Tests.ErrorValidations.loginErrorValidation(ErrorValidations.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="PracticeFrameWork.Tests.ErrorValidations" name="loginErrorValidation" time="7.961">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.base/java.io.File.<init>(File.java:278)
at PracticeFrameWork.TestComponents.BaseTest.getScreenshots(BaseTest.java:102)
at PracticeFrameWork.TestComponents.Listeners.onTestFailure(Listeners.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorValidation -->
</testsuite> <!-- Error Validations -->
